# Author: Aaron Yerke (aaronyerke@gmail.com)
# Main snakemake file for running and re-running scripts
# TODO Add defined variables to configfile to clean this up

# How do I force Snakemake to rerun all jobs from the rule I just edited? --forcerun or -R flag

configfile: "workflow/config/config.yaml"

import os
import pandas as pd

resp_colmns = ["beef_level", "TIMEPOINT"]
metabolomics_levels = ["chem", "sub_pathway","super_pathway"]
clean_sites = ["PSU_MED", "MB_IIT", "Purdue", "USDA_MED", "noMap", "noMB_noMap"]
clean_sites1 = ["PSU_MED", "MB_IIT", "Purdue", "USDA_MED", "noMap", "noMB_noMap"]
orgi_sites = ["PSU-MED", "MB/IIT", "Purdue", "USDA-MED"]
project_diet_prefix = ["", "mb-"]
# metabolomics_transforms = ["","log-"]
rf_columns = ["PARENT_SAMPLE_NAME", "SITE", "TIMEPOINT","TREATMENT","controls","beef_level","beef_level_oz"]
nutri_dir = os.path.join("data", "diet", "nutrition_data")
mapping_predictor_groups = ["rf_demographics_meats", "rf_meats"]
metabo_pred_dietarys = ["log-filt_all_bat_norm_imput", "demo-log-filt_all_bat_norm_imput"]
metabo_pred_cvds = ["meat-demo-log-filt_all_bat_norm_imput"]
cvd_prefix = "CVD"

rule completed:
	input:
# Nutrition data reorganization
		# os.path.join("data", "diet", "nutrition_data", "combined_esha_studies.tsv"),
		# expand("data/diet/nutrition_data/mb-{file}",\
		#    file=["HEI_with_proportions_long.tsv","HEI_with_proportions_long.xlsx", "HEI_with_proportions_long.tsv"]),
# Biomarker Rand Forest
		# w expand("output/no_map_auto_protein/tables/{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein_scores.csv",
		# metblmcs_lev=metabolomics_levels,clean_site=clean_sites),
		# expand("output/no_map_auto_protein/tables/shap_feat_imp_demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein.csv",
		# metblmcs_lev=metabolomics_levels),
		#midpoint for exp sankey autoproten
		# "data/mapping/noMap_metadata_auto-pro_demo.csv",
		# w expand("output/no_map_auto_protein/graphics/{clean_site}-metabolites_Sankey-auto_protein-{metblmcs_lev}.html",
		# metblmcs_lev=metabolomics_levels, clean_site=clean_sites),
		# "output/no_map_auto_protein/graphics/demo_plots.pdf",
		# "output/no_map_auto_protein/graphics/exp_org_Sankey.html",
# Random forest for CVD Markers
		# w expand("output/no_map_CVD/tables/{clean_site}-meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-CVD_scores.csv",
		# metblmcs_lev=metabolomics_levels,clean_site=clean_sites),
		# w expand("output/no_map_CVD/tables/{clean_site}-rf_demographics_meats-CVD_scores.csv",
		# clean_site=clean_sites),
		# "output/no_map_CVD/graphics/CVD_markers_plots.pdf",
		# expand("output/no_map_CVD/tables/{clean_site}-{metabo_pred_cvd}-{metblmcs_lev}-CVD_scores.csv",
		# metblmcs_lev=metabolomics_levels,
		# clean_site=clean_sites,
		# metabo_pred_cvd=metabo_pred_cvds)
		# w expand(f"output/no_map_CVD/graphics/{cvd_prefix}-{'{metblmcs_lev}'}-site_comparison.pdf",
		# metblmcs_lev=metabolomics_levels),
# For evaluating the models
		# w expand("output/ml_eval/tables/shap_feat_imp_train-{clean_site}_test-{clean_site1}_demo-log-filt_all_bat_norm_imput_vs_beef-chem-train_test_sep.csv",
		# clean_site=clean_sites, clean_site1=clean_sites1),
		expand("output/ml_eval/tables/rnd_shuf-{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein_scores.csv",
		metblmcs_lev=metabolomics_levels,clean_site=clean_sites),


rule combine_MB_dietary_to_single_table:
	conda:"env/python_conda_env.yml"
	input: "data/diet/mb/2112 Results.xlsx"
	output: "data/diet/nutrition_data/mb_2112_esha.tsv"
	shell:
		"""
		module load r
		Rscript scripts/harmonization/org_MB_dietary.R
		"""	
checkpoint correct_SR_ESHA_matches:
	input:
		"data/diet/nutrition_data/SR/hf_SR_best_matches_com LEO.xlsx",
		"data/diet/nutrition_data/best_matches/hf_SR_best_matches.xlsx"
	shell:
		"""
		Rscript scripts/harmonization/p5_correct_SR_ESHA_matches.R
		"""

rule imput_SRA_match:
	input:
		"data/diet/nutrition_data/HEI_with_proportions_long.xlsx",
		"data/diet/nutrition_data/SR/SR_food.csv"
	output:
		"data/diet/nutrition_data/best_matches/hf_SR_best_matches.xlsx"
	shell:
		"""
		Rscript scripts\harmonization\p4_imput_SRA_match_REST.py
		"""

rule automatic_label_proteins_USDA:
	input: expand("data/diet/nutrition_data/{file}",\
		   file=["HEI_conversion_table_LEO wide.xlsx",\
				 "esha_combined_meats_HEI_vals_LEO_noRed.xlsx"])
	output:
		expand("data/diet/nutrition_data/{file}",\
		   file=["HEI_with_proportions_long.tsv","HEI_with_proportions_long.xlsx"])
	shell:
		"""
		Rscript scripts/harmonization/p3_automatic_label_proteins.R
		"""

rule label_proteins_mb:
	input:
		conv = "data/diet/mb/mb-unique_esha_fped.tsv",
		diet = "data/diet/nutrition_data/mb-combined_esha_studies_HEI.tsv"
	output:
		"data/diet/nutrition_data/mb-esha_meats_FPED_vals.tsv",
	shell:
		"""
		module load r
		Rscript scripts/harmonization/p3.5_hand_label_proteins_mb.R\
			--FPED_conv {input.conv:q}\
			--out_prefix mb-
		"""

rule add_FPED_to_combined_ESHA_USDA:
	input:
		os.path.join("data", "diet", "nutrition_data", "HEI Pivot table_modified.xlsx"), 
		os.path.join("data", "diet", "nutrition_data", "combined_esha_studies.xlsx"),
	output:
		expand("data/diet/nutrition_data/{file}",\
		   file=["HEI_conversion_table_wide.tsv", "HEI_conversion_table.tsv",
		   "combined_esha_studies_HEI.tsv","HEI_missing_items.tsv"])
	shell:
		"""
		Rscript scripts/harmonization/p2_add_FPED_data.R
		"""

rule add_FPED_to_ESHA_MB:
	input:
		HEI_conv = "data/diet/nutrition_data/HEI Pivot table_modified.xlsx",
		diet = os.path.join("data", "diet", "nutrition_data", "mb_2112_esha.tsv"),
	output:
		expand("data/diet/nutrition_data/mb-{file}",\
		   file=["HEI_conversion_table_wide.tsv",
		   		"HEI_conversion_table_long.tsv","combined_esha_studies_HEI.tsv","HEI_missing_items.tsv"])
	shell:
		"""
		Rscript scripts/harmonization/p2_add_FPED_data.R\
			--HEI_conv {input.HEI_conv:q}\
			--input {input.diet:q}\
			--out_prefix mb-
		"""

rule combine_USDA_ESHA:
	input: os.path.join("data", "diet","map","MAP Study Complete ESHA Analysis Spreadsheet.xlsx"),
		   os.path.join("data", "diet","med","MED Diet Complete ESHA Analysis Spreadsheet.xlsx")
	output: multiext(os.path.join("data", "diet", "nutrition_data", "combined_esha_studies"), ".tsv", ".xlsx")
	shell:
		"""
		Rscript scripts/harmonization/p1_build_ESHA_csv.R
		"""

rule organize_response_data_beef_only:
	input: "data/metabolomics/UARS-01-23ML+/UARS-01-23ML+ DATA TABLES (ALL SAMPLES).XLSX"
	output: "data/mapping/full_metadata.csv",
			"data/mapping/noMap_metadata.csv",
			"data/mapping/rf_noMap_metadata.csv"
	params:
	shell:
		"""
		Rscript scripts/data_org/org_metadata_beef_only.R
		"""

rule organize_metabolomics:
	input:
		"data/metabolomics/UARS-01-23ML+/UARS-01-23ML+ DATA TABLES (DATA ADJUSTED BY BASELINE SAMPLES FROM EACH SITE).xlsx",
	output: "data/metabolomics/filt_all_bat_norm_imput-{metblmcs_lev}.csv",
			"data/metabolomics/log-filt_all_bat_norm_imput-{metblmcs_lev}.csv"
	shell:
		"""
		Rscript scripts/data_org/org_mtbmcs-{wildcards.metblmcs_lev}.R
		"""

rule organize_demographics:
	input: 
		"data/metabolomics/UARS-01-23ML+/UARS-01-23ML+ DATA TABLES (ALL SAMPLES).XLSX",
		"data/mapping/PSU demo.xlsx",
		"data/mapping/USDA PSU Med Beef Data.xlsx",
		"data/diet/mb/2112 V3    .csv", 
		"data/diet/mb/2112 V2 .csv", 
		"data/mapping/mb/MB-2112_Screen and Rand.xlsx",
		"data/mapping/purdue/AY_sample_codebook 9.12.2024 Campbell data.xlsx",
	output: "data/mapping/full_demo.csv",
			"data/mapping/noMap_demo.csv"
	shell:
		"""
		Rscript scripts/data_org/org_demo_help.R
		"""

rule combine_metadata_demo:
	conda:"env/python_conda_env.yml"
	input:
		diet_org = "data/mapping/noMap_demo.csv",
		helper = "data/mapping/noMap-meats.csv"
	output:
		"data/mapping/noMap-meats-demo.csv"
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		Rscript scripts/data_org/combine_2_csv.R\
			--first_path {input.diet_org}\
			--secnd_path {input.helper}\
			--out_path {output}\
			--id_var PARENT_SAMPLE_NAME
		"""

rule combine_auto_pro_demo:
	conda:"env/python_conda_env.yml"
	input:
		diet_org = "data/mapping/noMap_demo.csv",
		helper = "data/mapping/noMap-meats.csv"
	output:
		"data/mapping/noMap_metadata_auto-pro_demo.csv"
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		Rscript scripts/data_org/combine_2_csv.R\
			--first_path {input.diet_org}\
			--secnd_path {input.helper}\
			--out_path {output}\
			--id_var PARENT_SAMPLE_NAME
		"""

rule combine_metabol_demo:
	# conda:"env/python_conda_env.yml"
	input:
		diet_org = "data/metabolomics/log-filt_all_bat_norm_imput-{metblmcs_lev}.csv",
		helper = "data/mapping/noMap_demo.csv"
	output:
		"data/metabolomics/demo-log-filt_all_bat_norm_imput-{metblmcs_lev}.csv"
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		Rscript scripts/data_org/combine_2_csv.R\
			--first_path {input.diet_org}\
			--secnd_path {input.helper}\
			--out_path {output}\
			--id_var PARENT_SAMPLE_NAME
		"""

rule random_forest_cvd_metabol:
	input:
		predictor = "data/metabolomics/meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}.csv",
		response = "data/CVD/modified/{clean_site}-rf_cvd_markers.csv"
	output:
		"output/no_map_CVD/tables/feat_imp_{clean_site}-meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-CVD.csv",
		"output/no_map_CVD/tables/shap_feat_imp_{clean_site}-meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-CVD.csv",
		"output/no_map_CVD/tables/{clean_site}-meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-CVD_scores.csv"
	params:
		label = "{clean_site}-meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}_CVD"
	resources:
		runtime=2880, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="100gb",
		partition="short"
	shell:
		"""
			python scripts/ml/random_forest_cross_val.py \
				--pred_path {input.predictor} \
				--output_label {params.label} \
				--response_fn {input.response} \
				--out_folder no_map_CVD \
				--delimiter , \
				--title "{params.label}" \
				--id_var "PARENT_SAMPLE_NAME"
		"""

rule random_forest_auto_protein:
	input:
		response = "data/mapping/{clean_site}-rf_meats.csv",
		predictor = "data/metabolomics/demo-log-filt_all_bat_norm_imput-{metblmcs_lev}.csv"
	output:
		"output/no_map_auto_protein/tables/{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein_scores.csv",
		"output/no_map_auto_protein/tables/shap_feat_imp_{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein.csv",
		"output/no_map_auto_protein/tables/feat_imp_{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein.csv"
	params:
		label = "{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein"
	resources:
		runtime=1000, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="100gb",
		partition="short"
	shell:
		"""
			python scripts/ml/random_forest_cross_val.py \
				--pred_path {input.predictor} \
				--output_label {params.label} \
				--response_fn {input.response} \
				--out_folder no_map_auto_protein \
				--delimiter , \
				--title "{params.label}" \
				--id_var "PARENT_SAMPLE_NAME"
		"""

rule plot_demo_data:
	input: "data/mapping/noMap_metadata_auto-pro_demo.csv"
	output:
		"output/no_map_auto_protein/graphics/demo_plots.pdf"
	params:
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		   Rscript scripts/ds_descrip/demo_descr.R --data {input[0]} \
		   --output_fpath {output[0]}
		"""
rule plot_cvd_markers:
	input: "data/CVD/modified/noMap-cvd_markers.csv"
	output:
		"output/no_map_CVD/graphics/CVD_markers_plots.pdf"
	params:
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		   Rscript scripts/ds_descrip/demo_descr.R --data {input[0]} \
		   --output_fpath {output[0]}
		"""

rule exp_org_Sankey:#Sankey shows experimental organization
	input: "data/mapping/noMap-meats.csv"
	output:
		"output/no_map_auto_protein/graphics/exp_org_Sankey.html"
	params:
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		   Rscript scripts/ds_descrip/exp_org_Sankey.R --input {input[0]}\
		   		--output_dir no_map_auto_protein
		"""

rule comb_output_Sankey:#Compares top hits of feature importance for RF run
	conda:"env/python_conda_env.yml"
	input:
		"output/no_map_chick_is_not_beef/tables/demo-log-filt_all_bat_norm_imput-{metblmcs_lev}_scores.csv"
	output:
		"output/no_map_chick_is_not_beef/graphics/metabolites_Sankey-{metblmcs_lev}.html"
	shell:
		"""
			Rscript scripts/ds_descrip/comb_output_Sankey.R\
				--featimp_path {input[0]}\
				--output_dir no_map_chick_is_not_beef\
				--out_name metabolites_Sankey-{wildcards.metblmcs_lev}.html
		"""

# Rscript scripts/ds_descrip/comb_output_Sankey.R\
# 				--featimp_path output/ml_eval/tables/reorg-Avg_dystolic-shap_feat_imp-rf_demographics_meats--.csv\
# 				--output_dir no_map\
# 				--out_name Sankey-all_sites_ave_dpb_TESTING.html\
# 				--grouping_column SITE


rule org_auto_protein_label_response_data:
	input: 
		"data/diet/nutrition_data/esha_combined_meats_HEI_vals28Sep2023.tsv",
		"data/diet/nutrition_data/mb-esha_meats_FPED_vals.tsv",
		"data/mapping/mb/MB-2112_Screen and Rand.xlsx"
	output: 
		expand("data/mapping/{clean_site}-rf_meats.csv", clean_site=clean_sites),
		expand("data/mapping/{clean_site}-meats.csv", clean_site=clean_sites),
		"data/diet/nutrition_data/meat_total_participant.csv",
		expand("data/mapping/{clean_site}-rf_demographics_meats.csv", clean_site=clean_sites)
	params:
	shell:
		"""
		Rscript scripts/data_org/org_metadata_auto_protn.R
		"""

rule comb_output_Sankey_auto_label_protein:#Compares top hits of feature importance for RF run
	conda:"env/python_conda_env.yml"
	input:
		"output/no_map_auto_protein/tables/{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein-auto_protein_scores.csv"
	output:
		"output/no_map_auto_protein/graphics/{clean_site}-metabolites_Sankey-auto_protein-{metblmcs_lev}.html"
	params:
		label = "auto_protein"
	shell:
		"""
			Rscript scripts/ds_descrip/comb_output_Sankey.R\
				--featimp_path {input[0]}\
				--output_dir no_map_auto_protein\
				--out_name metabolites_Sankey-auto_protein-{wildcards.metblmcs_lev}.html
		"""
				
rule PCA_plot_numeric_meats:#Compares top hits of feature importance for RF run
	conda:"env/python_conda_env.yml"
	input:
		"data/mapping/noMap-meats.csv"
	output:
		"output/no_map_chick_is_not_beef/graphics/metabolites_Sankey-{metblmcs_lev}.html"
	shell:
		"""
			Rscript scripts/ds_descrip/comb_output_Sankey.R\
				--featimp_path {input[0]}\
				--output_dir no_map_chick_is_not_beef\
				--out_name metabolites_Sankey-{wildcards.metblmcs_lev}.html
		"""

rule random_forest_metadata_cvd_demo_meat:
	input:
		response = "data/CVD/modified/{clean_site}-rf_cvd_markers.csv",
		predictor = "data/mapping/{clean_site}-rf_demographics_meats.csv"
	output:
		"output/no_map_CVD/tables/{clean_site}-rf_demographics_meats-CVD_scores.csv",
		"output/no_map_CVD/tables/shap_feat_imp_{clean_site}-rf_demographics_meats-CVD.csv",
		"output/no_map_CVD/tables/feat_imp_{clean_site}-rf_demographics_meats-CVD.csv"
	params:
		label = "{clean_site}-rf_demographics_meats-CVD"
	resources:
		runtime=1000, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="100gb",
		partition="short"
	shell:
		"""
			python scripts/ml/random_forest_cross_val.py \
				--pred_path {input.predictor} \
				--output_label {params.label} \
				--response_fn {input.response} \
				--out_folder no_map_CVD \
				--delimiter , \
				--title "{params.label}" \
				--id_var "PARENT_SAMPLE_NAME"
		"""

rule org_cvd_response_data:
	input: 
		"data/mapping/noMap-meats.csv",
	output: 
		expand("data/CVD/modified/{clean_site}-rf_cvd_markers.csv", clean_site=clean_sites),
		# expand("data/CVD/modified/{clean_site}-cvd_markers.csv", clean_site=clean_sites)
	params:
	shell:
		"""
		Rscript scripts/CVD_markers/org_CVD_marker.R
		"""

rule combine_metabol_demo_meat:
	# conda:"env/python_conda_env.yml"
	input:
		diet_org = "data/metabolomics/demo-log-filt_all_bat_norm_imput-{metblmcs_lev}.csv",
		helper = "data/diet/nutrition_data/meat_total_participant.csv"
	output:
		"data/metabolomics/meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}.csv"
	resources:
		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="16gb"
	shell:
		"""
		Rscript scripts/data_org/combine_2_csv.R\
			--first_path {input.diet_org}\
			--secnd_path {input.helper}\
			--out_path {output}\
			--id_var PARENT_SAMPLE_NAME
		"""

rule compare_sites_cvd:
	input:
		expand("output/no_map_CVD/tables/{clean_site}-meat-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-CVD_scores.csv",
		metblmcs_lev=metabolomics_levels,clean_site=clean_sites),
	output:
		f"output/no_map_CVD/graphics/{cvd_prefix}-{'{metblmcs_lev}'}-site_comparison.pdf"
	params:
		prefix = cvd_prefix
	shell:
		"""
		Rscript /project/nhanes_ml/beef_biomarkers/scripts/ds_descrip/compare_site_scores.R\
			--metblmcs_lev {wildcards.metblmcs_lev}\
			--in_dir output/no_map_CVD/tables/\
			--out_subdir output/no_map_CVD/graphics/\
			--out_prefix {params.prefix}
		"""

# rule combine_rf_results_by_resp_var_auto_protein:
# 	input:
# 		expand("output/no_map_auto_protein/tables/feat_imp_{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein.csv",
# 		metblmcs_lev=metabolomics_levels,clean_site=clean_sites, metabo_pred_dietary=metabo_pred_dietarys),
# 	output:
# 		f"output/no_map_CVD/graphics/{cvd_prefix}-{'{metblmcs_lev}'}-site_comparison.pdf"
# 	params:
# 		prefix = cvd_prefix
# 	shell:
# 		"""
# 		Rscript /project/nhanes_ml/beef_biomarkers/scripts/ds_descrip/compare_site_scores.R\
# 			--metblmcs_lev {wildcards.metblmcs_lev}\
# 			--in_dir output/no_map_CVD/tables/\
# 			--out_subdir output/no_map_CVD/graphics/\
# 			--out_prefix {params.prefix}
# 		"""
# rule random_forest_cvd_meat:
# 	input:
# 		response = "data/CVD/modified/{clean_site}-rf_cvd_markers.csv",
# 		predictor = "data/mapping/{clean_site}-rf_meats.csv"
# 	output:
# 		"output/no_map_CVD/tables/{clean_site}-meat_only-{metblmcs_lev}-CVD_scores.csv",
# 		"output/no_map_CVD/tables/shap_feat_imp_{clean_site}-meat_only-{metblmcs_lev}-CVD.csv",
# 		"output/no_map_CVD/tables/feat_imp_{clean_site}-meat_only-{metblmcs_lev}-CVD.csv"
# 	params:
# 		label = "{clean_site}-meat_only-{metblmcs_lev}-CVD"
# 	resources:
# 		runtime=1000, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
# 		mem="100gb",
# 		partition="short"
# 	shell:
# 		"""
# 			python scripts/ml/random_forest_cross_val.py \
# 				--pred_path {input.predictor} \
# 				--output_label {params.label} \
# 				--response_fn {input.response} \
# 				--out_folder no_map_CVD \
# 				--delimiter , \
# 				--title "{params.label}" \
# 				--id_var "PARENT_SAMPLE_NAME"
# 		"""

# rule combine_meats_demo:
# 	conda:"env/python_conda_env.yml"
# 	input:
# 		diet_org = "data/mapping/noMap_demo.csv",
# 		helper = "data/mapping/noMap-meats.csv"
# 	output:
# 		"data/mapping/noMap_metadata_auto-pro_demo.csv"
# 	resources:
# 		runtime=60, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
# 		mem="16gb"
# 	shell:
# 		"""
# 		Rscript scripts/data_org/combine_2_csv.R\
# 			--first_path {input.diet_org}\
# 			--secnd_path {input.helper}\
# 			--out_path {output}\
# 			--id_var PARENT_SAMPLE_NAME
# 		"""

rule create_randomize_meats:
	input:
		"data/mapping/{clean_site}-rf_meats.csv"
	output:
		"data/mapping/shuff_PSN-{clean_site}-rf_meats.csv"
	shell:
		"""
		Rscript scripts/data_org/shuffle_column.R\
			--in_csv {input[0]} \
			--out_file {output[0]}
		"""

rule random_forest_rnd_shuf_auto_protein:
	input:
		response = "data/mapping/shuff_PSN-{clean_site}-rf_meats.csv",
		predictor = "data/metabolomics/demo-log-filt_all_bat_norm_imput-{metblmcs_lev}.csv"
	output:
		"output/ml_eval/tables/rnd_shuf-{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein_scores.csv",
		"output/ml_eval/tables/shap_feat_imp_rnd_shuf-{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein.csv",
		"output/ml_eval/tables/feat_imp_rnd_shuf-{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein.csv"
	params:
		label = "rnd_shuf-{clean_site}-demo-log-filt_all_bat_norm_imput-{metblmcs_lev}-auto_protein"
	resources:
		runtime=1000, #format: M, M:S, H:M:S, D-H, D-H:M, or D-H:M:S
		mem="100gb",
		partition="short"
	shell:
		"""
			python scripts/ml/random_forest_cross_val.py \
				--pred_path {input.predictor} \
				--output_label {params.label} \
				--response_fn {input.response} \
				--out_folder ml_eval \
				--delimiter , \
				--title "{params.label}" \
				--id_var "PARENT_SAMPLE_NAME"
		"""
\
rule create_rand_frst_train_test_seperate_sites_chem_beef:
	input:
		pred_train = "data/metabolomics/demo-log-filt_all_bat_norm_imput-chem.csv",
		resp_train = "data/mapping/{clean_site}-rf_auto_protn_metadata.csv",
		pred_test = "data/metabolomics/demo-log-filt_all_bat_norm_imput-chem.csv",
		resp_test = "data/mapping/{clean_site1}-rf_auto_protn_metadata.csv",
	output:
		"output/ml_eval/tables/shap_feat_imp_train-{clean_site}_test-{clean_site1}_demo-log-filt_all_bat_norm_imput_vs_beef-chem-train_test_sep.csv"
	params:
		out_label = "train-{clean_site}_test-{clean_site1}_demo-log-filt_all_bat_norm_imput_vs_beef-chem-train_test_sep"
	shell:
		"""
		python scripts/ml/rand_frst_train_test_specify.py\
			--pred_train {input.pred_train}\
			--pred_test {input.pred_test}\
			--response_train_fn {input.resp_train}\
			--response_test_fn {input.resp_test}\
			--output_label {params.out_label} \
			--response_col beef \
			--out_folder ml_eval \
			--delimiter , \
			--id_var PARENT_SAMPLE_NAME 
		"""

		

	
