#This was a big help: https://github.com/jdblischak/smk-simple-slurm/blob/main/simple/config.v8%2B.yaml#L5
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p slurmLogs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=slurmLogs/{rule}/%j.{wildcards}.log
    --error=slurmLogs/{rule}/%j.{wildcards}.log
    --time={resources.runtime}
    --mail-user=aaron.yerke@usda.gov
    --account=nhanes_ml
    --mail-type=END,FAIL
    --parsable
    # --software-deployment-method conda
default-resources:
  - partition=ceres
  - mem_mb=1000
  - runtime=120 #num minutes
  - nodes=1
  - ntasks=1
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 150
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: FALSE
# conda: "python_conda_env.yml"
